---
title: "Getting started"
author: "DBlana"
date: "23/07/2020"
output: html_document
---

# Getting started

## Naming files and folders {#names}

There are three main principles for good file names. They should be:

**1. Human readable**

+ Choose names that are related to the content of the file. Is it a file of demographic data? Don't call it "Dimitra's data.csv". Call it "demographics.csv".
+ Use hyphens "-" to separate words so the file names are easier to read. For example, if you have a file with code that loads and cleans your demographic data, you could call it "load-clean-demographics.r". It's easier than "loadcleandemographics.r". And it's definitely more relevant than "Dimitra's data analysis.r" 

**2. Machine readable**

+ Avoid spaces, punctuation, and any unusual characters.
+ Use underscores "_" as delimiters to separate units of metadata. For example, if you have data from different groups, dates and clinics in separate files, you have three units of metadata (group, date and clinic), and a good file name would be: "2020-08-04_group01_clinic04.csv"  

**3. Sortable**

+ If you have a date in your file name, put the date first, and make sure it's in the YYYY-MM-DD standard, so your files are ordered chronologically.
+ If you have numbers, pad with zeros (01,02,...,09,10,11,... instead of 1,2,...,9,10,11,...) to make sure they are ordered correctly.


## Project organisation {#folders}
The folder structure is designed from the ACHDS researcher perspective with Grampian Data Safe Haven (DaSH) elements incorporated as appropriate.  The folder names and overall structure would be the same across ACHDS and DaSH. 

Further details of the contents of each folder can be found in the table at the bottom of this document. 

The terms used in this paper are also recorded in the draft [ACHDS / DaSH dictionary](https://365abdn.sharepoint.com/teams/coviData/_layouts/15/Doc.aspx?sourcedoc=%7B7D86F582-2DC2-4829-9D54-36C6F57269CA%7D&file=DaSH%20Dictionary.docx&action=default&mobileredirect=true&CT=1623049838629&OR=ItemsView) which can be found in the Data Lab Shared Drive on Teams and Sharepoint. 

Each new project in DaSH will be accompanied by this document, so that the researcher can clearly see and follow the structure.  It will also be published in the ACHDS Guidebook for researchers and students. DaSH plans to write a process incorporating this document for DaSH staff.   

### Projects not related to DaSH 

¦--  PrimaryResearchData 
¦	¦--  Data DocumentationTemplate 
¦--  Methods 
¦--  ProcessedData 
¦	¦--  Data DocumentationTemplate (updated from Primary Research Data template) 
¦--  PermissionsDocumentation 
¦--  ProjectRelatedInformation 
¦--  Outputs 
¦	¦--  FakeDatasets 
¦	¦--  Data DocumentationTemplate for processed data or fake dataset if published. 
¦	¦--  Publications 

### DaSH Internal Structure (Modified structure for use within DaSH). 

¦--  DaSH_PrimaryResearchData  
¦	¦--  DaSH_ Release_Folders (Repeatable) 
¦		¦--  DaSH_SummaryStatistics 
¦		¦--  DaSH_DataDocumentation 
¦--  DaSH_Methods 
¦--  DaSH_ProcessedData 
¦		¦--  Data Documentation Template for DaSH Processed Data (updated from file provided as part of primary data.) 
¦--  DaSH_Outputs 

 ###DaSH Related Projects (Full structure for researchers) 

¦--  DaSH_PrimaryResearchData 
¦	¦--  DaSH_ Release_Folders (Repeatable) 
¦		¦--  DaSH_SummaryStatistics 
¦		¦--  DaSH_DataDocumentation 
¦--  PrimaryResearchData 
¦--  DaSH_Methods 
¦--  Methods 
¦--  DaSH_ProcessedData 
¦		¦--  Data Documentation Template (updated from file provided as part of primary data.) 
¦--  ProcessedData 
¦--  PermissionsDocumentation 
¦--  ProjectRelatedInformation 
¦--  DaSH_Outputs 
¦--  Outputs 
¦	¦--  FakeDatasets 
¦	¦--  Data DocumentationTemplate for processed data or fake dataset if published. 
¦	¦--  Publications 

### Folder Contents & Associated Terminology 

|Folder | Contents |
|------------ | -------------|
|DaSH_SummaryStatistics | Information that can be directly extracted from the dataset. For example, names of variables, range of variables and a note of missing data.  <br/>(Please note that the range is based on information in the dataset itself, so any errors in the dataset could lead to errors in the intended range.) <br/>Formerly known as ‘DaSH_Metadata’. |
|DaSH_DataDocumentation | Readme File and/or Data Documentation Template for Primary Data.<br/>See: https://github.com/AbdnCHDS/DataDocumentationTemplate  
|DaSH_Methods | Code and documentation |
|DaSH_Outputs | Data given to DaSH by the researcher after analysis, checked by DaSH and turned into an ‘output’. This means it can come out of the Safe Haven and put in the researcher folder. |
|DaSH_PrimaryResearchData | Data which is not yet processed by researcher.<br/>Data processed and linked by DaSH and then released to researchers – Files not to be amended. May be versioned as the researcher and analyst clarify what information is needed and updates are provided. |
|DaSH_ProcessedData | Files prepared by the researcher for transferring out of the Safe Haven.  DaSH team check the files and then transfer them. |
|DaSH_ Release_Folders | One folder per release usually associated with a date.<br/>Release folders may each need their own Metadata and Definitions subfolders as the merging of datasets is sometimes done by analysts and sometimes done by researchers.<br/>A Release = anything put in a folder on behalf of a researcher. The file given to the researcher as an output.  Might be a linkage of many datasets from different points and is merged. 
|FakeDatasets | |
|Methods | Code and documentation |
|Outputs | DaSH Outputs worked on by researcher.  Final version for publication. This folder only lives outside of DaSH. |  
|PermissionsDocumentation | For example, North Node Privacy Advisory Committee (NNPAC), Privacy and Public Benefit Panel (PPBP).<br/>NNPAC is an example of a “local” permissions body (LPAC) and PPBP is an example of a national permissions provider. |
|PrimaryResearchData |Data not sourced from DaSH. Files not to be amended. |
|ProcessedData | Data that has been processed by the researcher, for example, cleaning prior to analysis.| 
|ProjectRelatedInformation | Grants etc., financial records, important emails, private information. |
